#!/bin/bash
T="$(date +%s)"

find ./src/ -name '*.cpp' -o -name '*.c' -o -name '*.hpp' -o -name '*.h' > /tmp/cscope.files ;
find ./include/ -name '*.cpp' -o -name '*.c' -o -name '*.hpp' -o -name '*.h' >> /tmp/cscope.files ;
find /usr/include -name '*.cpp' -o -name '*.c' -o -name '*.hpp' -o -name '*.h' >> /tmp/cscope.files ;
mv /tmp/cscope.files .

# cscope -b -q -k ;
cscope -b
CSCOPE_DB=./cscope.out ; export CSCOPE_DB
echo "Generated cscope db with $? status!"
ctags --language-force=C++ -R ./ ;
echo "Generated ctags db with $? status!"

T="$(($(date +%s)-T))"
echo "It took ${T} seconds!"
