ARDUINO_PORT           = /dev/ttyUSB0
BOARD_TAG              = pro328
ARDUINO_DIR            = /usr/share/arduino
ARDUINO_LIBS           = RF24 SPI DHT11
MONITOR_BAUDRATE	     = 115200
#MCU                    = atmega328p
#F_CPU                  = 16000000
#AVRDUDE_ARD_BAUDRATE   = 115200
#AVRDUDE_ARD_PROGRAMMER = arduino

# If you have your additional libraries relative to your source, rather
# than in your "sketchbook", also set USER_LIB_PATH, like this example:
#
#        USER_LIB_PATH := $(realpath ../../libraries)

include /usr/share/arduino/Arduino.mk
