ARDUINO_PORT           = /dev/ttyUSB0
BOARD_TAG              = pro328
ARDUINO_DIR            = /usr/share/arduino
ARDUINO_LIBS           = RF24 SPI DHT11
MONITOR_BAUDRATE	     = 115200

include /usr/share/arduino/Arduino.mk
