#!/bin/bash
T="$(date +%s)"


find ./ -name '*.cpp' -o -name '*.c' -o -name '*.hpp' -o -name '*.h' > cscope.files ;
find /usr/share/arduino/libraries/ -name '*.cpp' -o -name '*.c' -o -name '*.hpp' -o -name '*.h' >> cscope.files ;
find /usr/share/arduino/hardware/arduino/cores/arduino/ -name '*.cpp' -o -name '*.c' -o -name '*.hpp' -o -name '*.h' >> cscope.files ;

# cscope -b -q -k ;
cscope -b
CSCOPE_DB=./cscope.out ; export CSCOPE_DB
echo "Generated cscope db with $? status!"
ctags --language-force=C++ -R ./ ;
echo "Generated ctags db with $? status!"

T="$(($(date +%s)-T))"
echo "It took ${T} seconds!"
